/*
 * ili9341_background.h
 *
 *  Created on: Feb 5, 2021
 *      Author: fil
 */

#ifndef INC_SINTMATE_ILI9341_BACKGROUND_H_
#define INC_SINTMATE_ILI9341_BACKGROUND_H_

#include "main.h"

#define	BACKGROUND_IMAGE_SIZE	300
#define	BACKGROUND1_SECTOR		16
#define	BACKGROUND2_SECTOR		BACKGROUND1_SECTOR+BACKGROUND_IMAGE_SIZE
#define	BACKGROUND3_SECTOR		BACKGROUND2_SECTOR+BACKGROUND_IMAGE_SIZE
#define	BACKGROUND4_SECTOR		BACKGROUND3_SECTOR+BACKGROUND_IMAGE_SIZE

extern	void LoadBackgroundImage(uint16_t background_index);

#endif /* INC_SINTMATE_ILI9341_BACKGROUND_H_ */
